from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "afb31428e42d"
down_revision: Union[str, Sequence[str], None] = "8efdf7ab94f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_page_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("page_id", sa.Integer(), nullable=False),
        sa.Column(
            "viewed_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_page_history_page_id"),
        "user_page_history",
        ["page_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_page_history_user_id"),
        "user_page_history",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_page_history_viewed_at"),
        "user_page_history",
        ["viewed_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_page_history_viewed_at"), table_name="user_page_history"
    )
    op.drop_index(op.f("ix_user_page_history_user_id"), table_name="user_page_history")
    op.drop_index(op.f("ix_user_page_history_page_id"), table_name="user_page_history")
    op.drop_table("user_page_history")
    # ### end Alembic commands ###
